trigger: none
pr:
- master
- dev

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.json
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      windowsAmdBuildJobTimeout: 300
      windowsAmdTestJobTimeout: 120
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      windowsAmdBuildJobTimeout: 420
